"""HTML report generation for QReviewer."""

from typing import List
from jinja2 import Template
from .models import Finding


# HTML template for the review report
TEMPLATE = Template("""
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>QReviewer Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8f9fa;
        }
        .header {
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        .summary {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        .findings {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .finding {
            border-left: 4px solid #007bff;
            padding: 15px;
            margin: 15px 0;
            background: #f8f9fa;
            border-radius: 4px;
        }
        .finding.critical { border-left-color: #dc3545; }
        .finding.major { border-left-color: #fd7e14; }
        .finding.minor { border-left-color: #ffc107; }
        .finding.nit { border-left-color: #6c757d; }
        .finding.blocking { border-left-color: #dc3545; }
        .severity {
            font-weight: bold;
            text-transform: uppercase;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.8em;
        }
        .severity.critical, .severity.blocking { background: #dc3545; color: white; }
        .severity.major { background: #fd7e14; color: white; }
        .severity.minor { background: #ffc107; color: #212529; }
        .severity.nit { background: #6c757d; color: white; }
        .file-info {
            font-family: monospace;
            background: #e9ecef;
            padding: 8px 12px;
            border-radius: 4px;
            margin: 10px 0;
        }
        .message {
            margin: 10px 0;
            font-size: 1.1em;
        }
        .suggestion {
            background: #d1ecf1;
            border: 1px solid #bee5eb;
            border-radius: 4px;
            padding: 10px;
            margin: 10px 0;
        }
        .suggestion strong {
            color: #0c5460;
        }
        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }
        .stat {
            text-align: center;
            padding: 15px;
            background: #e9ecef;
            border-radius: 6px;
        }
        .stat-number {
            font-size: 2em;
            font-weight: bold;
            color: #495057;
        }
        .stat-label {
            color: #6c757d;
            font-size: 0.9em;
            text-transform: uppercase;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🔍 QReviewer Code Review Report</h1>
        <p>Automated code review generated by QReviewer</p>
    </div>

    <div class="summary">
        <h2>📊 Summary</h2>
        <div class="stats">
            <div class="stat">
                <div class="stat-number">{{ findings|length }}</div>
                <div class="stat-label">Total Findings</div>
            </div>
            {% set critical_count = findings | selectattr('severity', 'equalto', 'critical') | list | length %}
            {% set blocking_count = findings | selectattr('severity', 'equalto', 'blocking') | list | length %}
            <div class="stat">
                <div class="stat-number">{{ critical_count + blocking_count }}</div>
                <div class="stat-label">Critical/Blocking</div>
            </div>
            {% set major_count = findings | selectattr('severity', 'equalto', 'major') | list | length %}
            <div class="stat">
                <div class="stat-number">{{ major_count }}</div>
                <div class="stat-label">Major Issues</div>
            </div>
            {% set minor_count = findings | selectattr('severity', 'equalto', 'minor') | list | length %}
            <div class="stat">
                <div class="stat-number">{{ minor_count }}</div>
                <div class="stat-label">Minor Issues</div>
            </div>
        </div>
    </div>

    <div class="findings">
        <h2>🔍 Detailed Findings</h2>
        {% if findings %}
            {% for finding in findings %}
            <div class="finding {{ finding.severity.lower() }}">
                <div class="file-info">
                    📁 {{ finding.file }}
                    {% if finding.line_hint %}
                        :{{ finding.line_hint }}
                    {% endif %}
                    {% if finding.hunk_header %}
                        ({{ finding.hunk_header }})
                    {% endif %}
                </div>
                
                <div class="severity {{ finding.severity.lower() }}">
                    {{ finding.severity }}
                </div>
                
                <div class="message">
                    {{ finding.message }}
                </div>
                
                {% if finding.suggested_patch %}
                <div class="suggestion">
                    <strong>💡 Suggestion:</strong>
                    <pre>{{ finding.suggested_patch }}</pre>
                </div>
                {% endif %}
                
                <div style="margin-top: 10px; color: #6c757d; font-size: 0.9em;">
                    Category: {{ finding.category }} | Confidence: {{ "%.1f"|format(finding.confidence * 100) }}%
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p>🎉 No issues found! This code looks good.</p>
        {% endif %}
    </div>
</body>
</html>
""".strip())


def render_html(findings: List[Finding]) -> str:
    """
    Render findings into an HTML report.
    
    Args:
        findings: List of Finding objects to render
        
    Returns:
        HTML string containing the formatted report
    """
    return TEMPLATE.render(findings=findings)
